### ISSUE TITLE
video element playing faster in recorded clip 

### ISSUE THREAD

**Issue by TejasBob** [tungs/timecut#55] opened 2021-06-08 00:46 UTC
Hello @tungs,
 
I'm trying to record a page that plays a video on canvas using `requestAnimationFrame`.

Following is the HTML file that I'm trying to record with headless Google-Chrome & timecut.

```
<html>
  <body>
    <div>
      <canvas id="myCanvas" width="640" height="360"></canvas>
    </div> 
    <script>
        var mediaSource = "/home/bob/445329631.mp4";

        var muted = true;
        var canvas = document.getElementById("myCanvas"); 
        var ctx = canvas.getContext("2d");
        var videoContainer; 
        var video = document.createElement("video"); 
        video.src = mediaSource;
        video.autoplay = false; 
        video.loop = true; 
        video.muted = muted;
        videoContainer = {  
             video : video,
             ready : false,   
        };
        video.oncanplay = readyToPlayVideo; 
                                          
        function readyToPlayVideo(event){ 
            videoContainer.scale = Math.min(
                                 canvas.width / this.videoWidth, 
                                 canvas.height / this.videoHeight); 
            videoContainer.ready = true;
            requestAnimationFrame(updateCanvas);
        }

        function updateCanvas(){
            ctx.clearRect(0,0,canvas.width,canvas.height); 
            if(videoContainer !== undefined && videoContainer.ready){ 
                video.muted = muted;
                var scale = videoContainer.scale;
                var vidH = videoContainer.video.videoHeight;
                var vidW = videoContainer.video.videoWidth;
                var top = canvas.height / 2 - (vidH /2 ) * scale;
                var left = canvas.width / 2 - (vidW /2 ) * scale;
                ctx.drawImage(videoContainer.video, left, top, vidW * scale, vidH * scale);
            }
            requestAnimationFrame(updateCanvas);
        }
         video.play();
  </script>
  </body>
</html>
```

I'm using following command to record the page.
`timecut "file:///home/bob/test4.html" --viewport="1280,720" --executable-path="/usr/bin/google-chrome" --fps=25   --duration=5 --pipe-mode --pix-fmt=yuv420p --output=video_canvas_reqAnimFrame_25.mp4`

Here's the original video element.

https://user-images.githubusercontent.com/10771892/121102444-349a2700-c7c3-11eb-9ed7-ec159bc4e003.mp4

First, I recorded the page at 25 FPS using `--fps=25` and `--duration=5`. I got following. 

https://user-images.githubusercontent.com/10771892/121103719-1da90400-c7c6-11eb-897a-dbd08f1d2a15.mp4

Then, I recorded the same page at 60 FPS using `--fps=60` and `--duration=5`. I got following.

https://user-images.githubusercontent.com/10771892/121103440-90fe4600-c7c5-11eb-9073-2cf46b16ef6c.mp4

As you must have noticed, the video element on canvas is playing faster than usual in both recorded clips.
The video element plays faster than usual in 25 fps recording. And it plays even faster in 60 fps recording. 

Does [timeweb](https://github.com/tungs/timeweb) support recording of pages with video elements on canvas?
It seems like the video element is not playing in sync with the virtual timeline.
I tried multiple input video files. But all recordings had the same behavior.
What am I missing here?

Side Note:
There is one more way to play a video on canvas, i.e by using `setTimeout` function.
If I use `setTimeout(...)` to play video-element and render the page, it creates correct recording. But something is going wrong with `requestAnimationFrame` way of playing video.

I'm on Ubuntu 16.04 LTS, using Chrome Version 90.0.4430.212 (Official Build) (64-bit).
I'm using my Desktop chrome binary for headless recording ( instead of chromium).
Node Version v15.2.0
Timecut Version 0.2.0

**Comment by tungs** [comment] 2021-06-13 15:06
Big thanks for filing this @TejasBob! I took a look at it this weekend and saw faster-than-normal playback using both `requestAnimationFrame` and `setTimeout`. It is indeed a bug, and stems from `timeweb` exporting a customized `createElement` to `window` instead of `document`. Because of this, the video plays in real time. If the video gets added to the DOM, it should switch over to a virtual timeline as intended.

It looks like this bug was introduced when code was migrated to `timeweb`. It should be fixed in the next version of `timeweb` and `timecut`. A temporary fix would be either to add the video to DOM (you can make it invisible) or to downgrade to `timecut` v0.1.4, which was before the migration.

**Comment by tungs** [comment] 2021-06-14 05:04
The video should now play in virtual time instead of real time as of timeweb `v0.1.1`, (and the new timesnap/timecut `v0.2.1` should require this dependency). Let me know if it doesn't work. It's intriguing that `setTimeout` worked for you, while `requestAnimationFrame` didn't (both didn't work for me), but in any case they should both work now.

As a side note, the implementation that you have which uses `oncanplay` seems to be called every time the video is seeked. timeweb seeks for every frame, which causes `oncanplay` to be run multiple times. This creates an increasing number of requestAnimationFrame loops, (e.g. 50 loops on the 50th frame), which is probably not what is intended. This may be fixed in a subsequent version of timeweb (see tungs/timeweb#2), though for now, you probably should remove the listener after it's called for the first time (or you may not need to use a listener at all, since capturing should wait until the video seeks to correct frame).

**Closed** 2021-06-14 05:05 UTC
Labels: bug

**Comment by TejasBob** [comment] 2021-06-19 05:19
Thanks a lot, @tungs for such a quick update & release.
Agree with your comment on `oncanplay` thing.
